/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Inheritance } from "./Inheritance";
export * as factories from "./factories";
export { Inheritance__factory } from "./factories/Inheritance__factory";
